### PR TITLE
fix(webpack): improve cross plattform compatibility

### PR DESCRIPTION
**Pull request by dmbch**
We have seen an internal bug report of a Windows user, assumably caused by not properly escaping paths in `@untool/webpack`'s config loader:

```
ERROR in: ./node_modules/@untool/core/lib/config.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: C:\projects\foo\node_modules\@untool\core\lib\config.js: Bad character escape sequence
```

Strings resembling [escape sequences](https://mathiasbynens.be/notes/javascript-escapes) such as `\u` (and in XING's case, `\x`) are a rather common occurrence in Windows paths. This PR attempts to deal with such cases.

Caveat: since I currently have no Windows machine available, I was unable to validate this approach so far.

### CODE REVIEW

**Comment by M3nsch** [comment]
I just tested this on my windows machine and it seems to work just fine, compiling is successful.

However, i now encounter another error in runtime:
`Uncaught TypeError: __webpack_require__(...) is not a function
    at eval (webpack-internal:///./node_modules/core-js/modules/_is-regexp.js:6)
    at Object../node_modules/core-js/modules/_is-regexp.js (salary-5.js:4696)
    at __webpack_require__ (salary.js:787)
    at fn (salary.js:150)
    at eval (webpack-internal:///./node_modules/core-js/modules/es6.regexp.split.js:7)
    at Object../node_modules/core-js/modules/es6.regexp.split.js (salary-5.js:5820)
    at __webpack_require__ (salary.js:787)
    at fn (salary.js:150)
    at eval (webpack-internal:///./node_modules/core-js/modules/_redefine.js:1)
    at Object../node_modules/core-js/modules/_redefine.js (salary-5.js:5053)`

I'm not sure if this is another problem or related to this one.

**Comment by dmbch** [comment]
Moin @M3nsch, thanks for chiming in. This appears to be a separate issue. Would you mind cloning this repo/branch to your machine, install dependencies (`yarn`) and start the dev server (`yarn start`)?

I would like us to determine wether what you describe is an `untool` issue or something project specific.

**Comment by M3nsch** [comment]
Sure, there is the next windows related issue :)

When running `yarn` in the untool repo, i get this:

`$ [ -z "${npm_execpath##*yarn*}" ] || exit 1
Der Befehl "[" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
error Command failed with exit code 1.`

The preinstall script seems to be unix only.

**Comment by dmbch** [comment]
Sorry, I forgot! Please just delete the `postinstall` script from the package.json file.

**Comment by M3nsch** [comment]
`yarn start` gives
> yarn run v1.13.0  
$ cd tests/fixtures/untest; un start  
Das System kann den angegebenen Pfad nicht finden.  
error Command failed with exit code 1.

Running `un start` in the correct directory gives
> C:\projects\untool\tests\fixtures\untest>un start
SyntaxError: Invalid regular expression: /\/: \ at end of pattern
    at new RegExp (<anonymous>)
    at C:\projects\untool\node_modules\duplitect\index.js:37:18
    at Array.map (<anonymous>)
    at getAllDuplicates (C:\projects\untool\node_modules\duplitect\index.js:35:6)
    at getDuplicates (C:\projects\untool\node_modules\duplitect\index.js:55:20)
    at DuplicatePackagesDiagnosisMixins.diagnoseDuplicatePackages (C:\projects\untool\packages\info\lib\diagnoses\duplicates.js:13:24)
    at override (C:\projects\untool\node_modules\mixinable\index.js:37:15)
    at syncFn (C:\projects\untool\node_modules\mixinable\index.js:137:18)
    at Mixinable.callableSync (C:\projects\untool\node_modules\mixinable\index.js:87:42)
    at WebpackBuildMixin.diagnose (C:\projects\untool\packages\webpack\mixins\build\mixin.core.js:85:5)

**Comment by dmbch** [comment]
@M3nsch if you really want to continue down this rabbit hole..: I have just released and included a new version of the `duplitect` package that caused the last error.

**Comment by M3nsch** [comment]
Compling successful now.
> C:\projects\untool\tests\fixtures\untest>un start
untest:info running 'start' in 'development' mode
untest:info listening at http://localhost:8081/
untest:info bundling 'develop' finished after 8.9s
untest-0.js (3.85 MB)
untest-1.js (192 kB)
untest-2.js (2.61 kB)
untest-3.js (3.45 kB)
untest.js (114 kB)
untest:info bundling 'node' finished after 9s
server.js (2.49 MB)
stats.json (2.99 MB)

But: Opening `http://localhost:8081/` in Chrome does give the same error as reported by me above:  
  
image

**Comment by dmbch** [comment]
@M3nsch could you give it another try? Thanks for the screenshot, that was extremely helpful.

**Comment by M3nsch** [comment]
Running fine now, thank you!

image

👍

**Comment by dmbch** [comment]
@M3nsch thanks for confirming - and for your help. We will try to merge and publish this tomorrow.

**Pull request merged**
